### ISSUE TITLE
hw93 feedback

### ISSUE THREAD

**Issue by DavidHolmes0** [SajedNahian/Comatose-Barbarians_Nahian-S_Wargo-A#1]
## personnel
["Who are those guys?"](https://www.youtube.com/watch?v=-kbTbg00AJU)

## statement of problem
Returning the path should be considered tentative the specification for v0. Returning may emerge as a "free" consequence of how you program the required problem (namely, determining the Boolean value). But put yourself in the mindset of a client who wants the Boolean value but is waiting while some cowboy consultant programs and debugs a more complicated program that they don't need.

## recursive abstraction
I, too, was initially consider focussing on the junctions, which I still think could work. But it's more complicated that focussing on the stepping stones, so recommend relegating it to v*n*.

## base cases
Fill this in.

## English or pseudocode description of algorithm

The current version is seriously over-complicated, but probably that will be fixed by attending to the previous issues.

**Comment by SajedNahian** [comment]
personnel info added
